/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiPlanRouteImport } from './routes/api/ai-plan'
import { Route as ApiPublicGateActionRouteImport } from './routes/api/public/gate/$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPlanRoute = ApiAiPlanRouteImport.update({
  id: '/api/ai-plan',
  path: '/api/ai-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGateActionRoute = ApiPublicGateActionRouteImport.update({
  id: '/api/public/gate/$action',
  path: '/api/public/gate/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai-plan': typeof ApiAiPlanRoute
  '/api/public/gate/$action': typeof ApiPublicGateActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai-plan': typeof ApiAiPlanRoute
  '/api/public/gate/$action': typeof ApiPublicGateActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai-plan': typeof ApiAiPlanRoute
  '/api/public/gate/$action': typeof ApiPublicGateActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ai-plan' | '/api/public/gate/$action'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai-plan' | '/api/public/gate/$action'
  id: '__root__' | '/' | '/api/ai-plan' | '/api/public/gate/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiPlanRoute: typeof ApiAiPlanRoute
  ApiPublicGateActionRoute: typeof ApiPublicGateActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-plan': {
      id: '/api/ai-plan'
      path: '/api/ai-plan'
      fullPath: '/api/ai-plan'
      preLoaderRoute: typeof ApiAiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gate/$action': {
      id: '/api/public/gate/$action'
      path: '/api/public/gate/$action'
      fullPath: '/api/public/gate/$action'
      preLoaderRoute: typeof ApiPublicGateActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiPlanRoute: ApiAiPlanRoute,
  ApiPublicGateActionRoute: ApiPublicGateActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
